### ISSUE TITLE
Can't run PowerToys Run after installation

### ISSUE THREAD

**Issue by SonGokussj4** [bostrot/PowerToysRunPluginWinget#11]
I've downloaded the latest version 1.2.0, extracted and the folder copied to `C:\Program Files\PowerToys\modules\launcher\Plugins`.
Restarted PowerToys and I can't open the PowerRun functionality.
When I deleted the folder, restarted PowerToys, PowerRun still didn't work. I needed to disable it and enable it.
When I extracted this plugin again, restarted PowerToys, tried to disable and enable PowerRun, it still didn't work (windows didn't appear).
I've got custom shortcut to `ALT+F2`. Not sure if that's the problem.

**Comment by MJWexer** [comment]
I can confirm the same.
putting WinGet in "C:\Users\<user>\AppData\Local\PowerToys\modules\launcher\Plugins" folder kills PowerRun.
Removing WinGet and restarting PowerToys fixes the issue.

PowerToys: 0.70.1
Winget plugin: 1.2.0
Winget: https://apps.microsoft.com/store/detail/appinstallation/9NBLGGH4NNS1

*EDIT*
Tried reinstalling PowerToys to C:\Program Files\PowerToys and having it placed:
C:\Program Files\PowerToys\modules\launcher\Plugins\Winget
Then restarting computer
Same issue
Removing the Winget folder from the Plugins folder and restarting PowerToys restores PowerRunfunctionallity.

**Comment by culliganman814** [comment]
Also having the same issue, something else I'm noticing is that when I close PowerToys there is still an instance of PowerRun I have to kill in TaskManager to be able to remove the WinGet folder from the C:\Program Files\PowerToys\modules\launcher\Plugins directory

**Comment by bostrot** [comment]
[v1.2.1](https://github.com/bostrot/PowerToysRunPluginWinget/releases/tag/v1.2.1) should fix that. Can you test it?

**Comment by rasemaier** [comment]
no still not working

**Comment by smplrtrn** [comment]
Neither v.1.2.1 nor v.1.2.0 or any of the versions before are working with PT v0.70 or v0.70.1 here.

Looks like I've been being too late to the party to enjoy winget.

**Comment by bostrot** [comment]
Well, it works for me 🙃

What OS are you running?

**Comment by bostrot** [comment]
![image](https://github.com/bostrot/PowerToysRunPluginWinget/assets/7342321/24bb08da-a350-43a3-81bb-5d27cfb307c1)

Just to make sure, this is the folder structure:

C:\Program Files\PowerToys\modules\launcher\Plugins:

![image](https://github.com/bostrot/PowerToysRunPluginWinget/assets/7342321/7a5ca094-b967-414c-8a00-67e77334d89f)

**Comment by smplrtrn** [comment]
Hi bostrot, thanx for your attention

22H2 22631.1835  ist what System > About gives, this machine is running Insider Programme Beta   
Installed to C:\Program Files\PowerToys\modules\launcher\Plugins  
Exit and run PowerToys -> Failed to start Plugin Winget ... 
The PowerToysRun launcher is actually working, but Winget is not.

**Comment by MJWexer** [comment]
> [v1.2.1](https://github.com/bostrot/PowerToysRunPluginWinget/releases/tag/v1.2.1) should fix that. Can you test it?

Tested 1.2.1 same issue, still opens window menu (alt+space) for me instead of PowerToys Run. doenst help chanigng to another hotkey

Winver: 22H2 22621.1702
PowerToys: 0.70.1
Winget plugin: 1.2.1
Winget: https://apps.microsoft.com/store/detail/appinstallation/9NBLGGH4NNS1
Install location: C:\Program Files\PowerToys\modules\launcher\Plugins
Hotkey: alt+space

**Comment by smplrtrn** [comment]
I went down the rabbit hole to find out what is actually broken and it turned out the App Installer wouldn't run at all (tested via Powershell winget install some-app) - so this apparently needed to be fixed first.   
Microsoft Store wouldn't give an update for App Installer directly when clicking on Update, so inside Microsoft Store I went via Library - > Updates, found App Installer and went Update.   
Testing winget install in Powershell succeeded.

And Winget plugin is running on PowerToysRun now perfectly.

Thanx!

**Comment by MJWexer** [comment]
@smplrtrn, what version are you on after your App Installer update? I'm on 1.19.11071.0
More curious, I don't see WinGet in the list of plugins under the PowerToys Run menu.

**Comment by smplrtrn** [comment]
winget --version  
v1.4.11071  
App Installer is on 1.19.11071.0 (but apparently it was broken before I updated)

**Comment by MJWexer** [comment]
Hmm, I'm on the same version.

Disabling "Always run as administrator" means I can now see WinGet in my plugins list under the PT Run menu, but nothing happens when I try and trigger it.
Exiting PowerToys run, I still see PowerToys Run hanging in the process tree.
Removing the WinGet library from the Plugins folder resolves all problems.

Currently looking (unsuccessfully) for clues in:
%LOCALAPPDATA%/Microsoft/PowerToys/Settings/Logs/0.70.1.0/
%LOCALAPPDATA%/Microsoft/PowerToys/PowerToys Run/LogsModuleInterface/
%LOCALAPPDATA%/Microsoft/PowerToys/PowerToys Run/Logs/

I would appreciate any pointers you can provide.

Do you guys use the github or store versions of PT?

**Comment by MJWexer** [comment]
Fixed for me too!
I uninstalled PowerToys(Winget edition) and installed it using the .exe 

EDIT: The problem returned to me today once I used the "Run as Administrator" function built into PowerToys. Turning it off and returning to normal user privilege resolved the issue.

**Comment by bostrot** [comment]
> I went down the rabbit hole to find out what is actually broken and it turned out the App Installer wouldn't run at all (tested via Powershell winget install some-app) - so this apparently needed to be fixed first.   
> Microsoft Store wouldn't give an update for App Installer directly when clicking on Update, so inside Microsoft Store I went via Library - > Updates, found App Installer and went Update.   
> Testing winget install in Powershell succeeded.
> 
> And Winget plugin is running on PowerToysRun now perfectly.
> 
> Thanx!

Happy it works now! 
I guess I should implement some checking if winget is installed/working correctly as currently it just assumes it.

**Comment by sugardave** [comment]
I just installed this plugin today and ran into the same issue.  What solved it for me was to make sure the ACL for the `Winget` plugin folder and all its contents have `SYSTEM` as the owner..  Mine was set to my user account after copying it off a network share.  I can run PowerToys as administrator and have the working plugin.
